-- Migration 0002: update categories + seed ingredients

-- Categories
INSERT INTO ingredient_categories (id, name, sort_order) VALUES ('cat-1', 'Frugt & grønt', 1) ON CONFLICT(id) DO UPDATE SET name = excluded.name, sort_order = excluded.sort_order;
INSERT INTO ingredient_categories (id, name, sort_order) VALUES ('cat-2', 'Krydderier', 12) ON CONFLICT(id) DO UPDATE SET name = excluded.name, sort_order = excluded.sort_order;
INSERT INTO ingredient_categories (id, name, sort_order) VALUES ('cat-3', 'Mejeri & æg', 6) ON CONFLICT(id) DO UPDATE SET name = excluded.name, sort_order = excluded.sort_order;
INSERT INTO ingredient_categories (id, name, sort_order) VALUES ('cat-4', 'Kød & fisk', 3) ON CONFLICT(id) DO UPDATE SET name = excluded.name, sort_order = excluded.sort_order;
INSERT INTO ingredient_categories (id, name, sort_order) VALUES ('cat-5', 'Pålæg', 4) ON CONFLICT(id) DO UPDATE SET name = excluded.name, sort_order = excluded.sort_order;
INSERT INTO ingredient_categories (id, name, sort_order) VALUES ('cat-6', 'Brød & bagværk', 2) ON CONFLICT(id) DO UPDATE SET name = excluded.name, sort_order = excluded.sort_order;
INSERT INTO ingredient_categories (id, name, sort_order) VALUES ('cat-7', 'Ris & pasta', 15) ON CONFLICT(id) DO UPDATE SET name = excluded.name, sort_order = excluded.sort_order;
INSERT INTO ingredient_categories (id, name, sort_order) VALUES ('cat-8', 'Konserves', 14) ON CONFLICT(id) DO UPDATE SET name = excluded.name, sort_order = excluded.sort_order;
INSERT INTO ingredient_categories (id, name, sort_order) VALUES ('cat-9', 'Frost', 5) ON CONFLICT(id) DO UPDATE SET name = excluded.name, sort_order = excluded.sort_order;
INSERT INTO ingredient_categories (id, name, sort_order) VALUES ('cat-10', 'Øl & Sodavand', 10) ON CONFLICT(id) DO UPDATE SET name = excluded.name, sort_order = excluded.sort_order;
INSERT INTO ingredient_categories (id, name, sort_order) VALUES ('cat-11', 'Rengøring & husholdning', 18) ON CONFLICT(id) DO UPDATE SET name = excluded.name, sort_order = excluded.sort_order;
INSERT INTO ingredient_categories (id, name, sort_order) VALUES ('cat-12', 'Andet', 99) ON CONFLICT(id) DO UPDATE SET name = excluded.name, sort_order = excluded.sort_order;
INSERT INTO ingredient_categories (id, name, sort_order) VALUES ('cat-13', 'Ost', 7) ON CONFLICT(id) DO UPDATE SET name = excluded.name, sort_order = excluded.sort_order;
INSERT INTO ingredient_categories (id, name, sort_order) VALUES ('cat-14', 'Vin', 11) ON CONFLICT(id) DO UPDATE SET name = excluded.name, sort_order = excluded.sort_order;
INSERT INTO ingredient_categories (id, name, sort_order) VALUES ('cat-15', 'Personlig pleje', 19) ON CONFLICT(id) DO UPDATE SET name = excluded.name, sort_order = excluded.sort_order;
INSERT INTO ingredient_categories (id, name, sort_order) VALUES ('cat-16', 'Slik & chips', 20) ON CONFLICT(id) DO UPDATE SET name = excluded.name, sort_order = excluded.sort_order;
INSERT INTO ingredient_categories (id, name, sort_order) VALUES ('cat-17', 'Saft & juice', 9) ON CONFLICT(id) DO UPDATE SET name = excluded.name, sort_order = excluded.sort_order;
INSERT INTO ingredient_categories (id, name, sort_order) VALUES ('cat-18', 'Mel & bag', 17) ON CONFLICT(id) DO UPDATE SET name = excluded.name, sort_order = excluded.sort_order;
INSERT INTO ingredient_categories (id, name, sort_order) VALUES ('cat-19', 'Gryn & cereal', 8) ON CONFLICT(id) DO UPDATE SET name = excluded.name, sort_order = excluded.sort_order;
INSERT INTO ingredient_categories (id, name, sort_order) VALUES ('cat-20', 'Olie & sauce', 13) ON CONFLICT(id) DO UPDATE SET name = excluded.name, sort_order = excluded.sort_order;

-- Ingredients
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Æbler', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Bananer', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Appelsiner', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Citroner', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Lime', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Pærer', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Druer', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Jordbær', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Blåbær', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Hindbær', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Mango', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Avocado', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Tomater', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Cherrytomater', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Agurk', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Salat', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Rucola', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Spinat', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Gulerødder', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Broccoli', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Blomkål', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Hvidkål', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Rødkål', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Løg', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Rødløg', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Forårsløg', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Hvidløg', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Porrer', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Selleri', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Pastinak', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Rødbeder', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Radiser', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Peberfrugt rød', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Peberfrugt gul', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Peberfrugt grøn', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Habanerochili', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Jalapeno', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Squash', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Aubergine', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Majs', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Ærter', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Bønner grønne', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Kartofler', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Søde kartofler', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Svampe', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Champignon', 'cat-1');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Persille', 'cat-2');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Basilikum', 'cat-2');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Koriander', 'cat-2');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Timian', 'cat-2');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Rosmarin', 'cat-2');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Oregano', 'cat-2');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Dild', 'cat-2');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Mynte', 'cat-2');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Ingefær', 'cat-2');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Salt', 'cat-2');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Peber', 'cat-2');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Paprika', 'cat-2');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Spidskommen', 'cat-2');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Karry', 'cat-2');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Gurkemeje', 'cat-2');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Kanel', 'cat-2');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Chiliflager', 'cat-2');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Sennep', 'cat-2');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Mælk', 'cat-3');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Sødmælk', 'cat-3');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Madlavningsfløde', 'cat-3');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Piskefløde', 'cat-3');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Creme fraiche 18%', 'cat-3');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Creme fraiche 38%', 'cat-3');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Smør', 'cat-3');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Margarine', 'cat-3');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Hytteost', 'cat-3');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Skyr', 'cat-3');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Yoghurt naturel', 'cat-3');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Cremefraiche', 'cat-3');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Æg', 'cat-3');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Kyllingebryst', 'cat-4');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Kyllingelår', 'cat-4');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Hakket kylling', 'cat-4');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Oksekød hakket', 'cat-4');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Oksebøf', 'cat-4');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Svinekød hakket', 'cat-4');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Svinekotelet', 'cat-4');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Flæskesteg', 'cat-4');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Bacon', 'cat-4');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Lam hakket', 'cat-4');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Lammekølle', 'cat-4');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Laks', 'cat-4');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Torsk', 'cat-4');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Rejer', 'cat-4');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Rødspætte', 'cat-4');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Skinke', 'cat-5');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Spegepølse', 'cat-5');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Leverpostej', 'cat-5');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Salami', 'cat-5');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Rullepølse', 'cat-5');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Roastbeef', 'cat-5');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Franskbrød', 'cat-6');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Rugbrød', 'cat-6');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Grovbrød', 'cat-6');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Burgerboller', 'cat-6');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Pitabrød', 'cat-6');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Tortilla', 'cat-6');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Bagel', 'cat-6');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Ciabatta', 'cat-6');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Spaghetti', 'cat-7');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Penne', 'cat-7');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Fusilli', 'cat-7');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Lasagneplader', 'cat-7');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Ris', 'cat-7');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Basmatiris', 'cat-7');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Jasminris', 'cat-7');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Couscous', 'cat-7');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Bulgur', 'cat-7');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Quinoa', 'cat-7');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Kokosmælk på dåse', 'cat-8');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Hakkede tomater', 'cat-8');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Tomatpuré', 'cat-8');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Kidneybønner på dåse', 'cat-8');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Kikærter på dåse', 'cat-8');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Linser på dåse', 'cat-8');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Majs på dåse', 'cat-8');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Tun på dåse', 'cat-8');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Makrel i tomat', 'cat-8');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Ananas på dåse', 'cat-8');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Oliven', 'cat-8');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Kapers', 'cat-8');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Cornichoner', 'cat-8');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Hønsebouillon', 'cat-8');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Oksebouillon', 'cat-8');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Grøntsagsbouillon', 'cat-8');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Ærter frosne', 'cat-9');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Majs frosne', 'cat-9');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Spinat frosne', 'cat-9');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Blåbær frosne', 'cat-9');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Hindbær frosne', 'cat-9');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Pommes frites frosne', 'cat-9');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Fiskefrikadeller frosne', 'cat-9');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Øl', 'cat-10');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Cola', 'cat-10');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Sodavand', 'cat-10');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Mineralvand', 'cat-10');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Mozzarella', 'cat-13');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Feta', 'cat-13');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Parmesan', 'cat-13');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Rygeost', 'cat-13');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Danbo', 'cat-13');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Gouda', 'cat-13');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Emmentaler', 'cat-13');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Brie', 'cat-13');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Revet ost', 'cat-13');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Rødvin', 'cat-14');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Hvidvin', 'cat-14');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Rosévin', 'cat-14');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Juice appelsin', 'cat-17');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Juice æble', 'cat-17');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Smoothie', 'cat-17');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Saftevand', 'cat-17');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Hvedemel', 'cat-18');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Rugmel', 'cat-18');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Ølandshvedemel', 'cat-18');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Groft mel', 'cat-18');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Sukker', 'cat-18');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Flormelis', 'cat-18');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Bagepulver', 'cat-18');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Natron', 'cat-18');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Gær', 'cat-18');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Tørgær', 'cat-18');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Havregryn fine', 'cat-19');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Havregryn grove', 'cat-19');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Cornflakes', 'cat-19');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Mysli', 'cat-19');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Linser', 'cat-19');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Kikærter', 'cat-19');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Sorte bønner', 'cat-19');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Kidneybønner', 'cat-19');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Olivenolie', 'cat-20');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Rapsolie', 'cat-20');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Sesamolie', 'cat-20');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Soja', 'cat-20');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Worcestershiresauce', 'cat-20');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Tabasco', 'cat-20');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Hoisinsauce', 'cat-20');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Fishsauce', 'cat-20');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Jordnøddesmør', 'cat-20');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Syltetøj', 'cat-20');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Nutella', 'cat-20');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Slik', 'cat-16');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Chokolade', 'cat-16');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Chips', 'cat-16');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Kaffe', 'cat-12');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Te', 'cat-12');
INSERT OR IGNORE INTO ingredients (id, name, category_id) VALUES (lower(hex(randomblob(16))), 'Vand', 'cat-12');
